### PR TITLE
Changes for the latest klipper and update the code for Python3

### PR DESCRIPTION
**Pull request by loganmac**
Hello! I had a few problems trying to get this working with the latest upstream klipper. I think because it was on Python 3 now instead of 2. I updated the code until it worked! Successfully running klipper on my Prusa Mini now with this - thanks for doing the hard part! 😄 

Some things may not be very idiomatic - I'm not very well versed in Python, I just let the error messages guide me to victory.

### CODE REVIEW

**Comment by matthewlloyd** [comment]
Thanks for doing this. I can't merge this as it is without us having to do some work to separate out the changes, have you explain me how you resolved the merge conflicts, write things in idiomatic Python 3 and so on. In the interest of efficiency, I just analyzed the fixes you made (thanks!) and have created a new branch in the repo which incorporates Klipper upstream changes and fixes the Python 3 incompatibilities you encountered:

prusamini-python3

The challenge is, I am no longer a Prusa Mini owner... could you please test it for me and let me know if it works?

**Comment by loganmac** [comment]
@matthewlloyd perfect! That’s what I was hoping you will do. I will test it for sure tonight. I’m also trying to be a squeaky wheel in the Klipper discord to get reviews on your PR there.

**Comment by marcboivin** [comment]
Tested prusamini-python3 branch. Works fine so far: flashed correctly, homing, screen, control on screen. Will start a print now.

**Comment by marcboivin** [comment]
Completed a print. No issue whatsoever. Anything I should test to give you guys feedback?

**Comment by matthewlloyd** [comment]
@marcboivin Many thanks for testing. I think this is low risk given flashing, homing, screen, control, and printing all worked for you without issue. I have merged the changes into the main prusamini branch and am closing this PR.

**Pull request closed without merging**
